# Generated by Django 4.2 on 2023-11-03 20:53

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ListBasculas",
            fields=[
                ("id_basculas", models.AutoField(primary_key=True, serialize=False)),
                ("ip_bascula", models.CharField(max_length=45)),
                ("port_bascula", models.IntegerField()),
                ("nombre_bascula", models.CharField(max_length=45)),
                ("ubicacion", models.CharField(max_length=50)),
                ("departamento", models.CharField(max_length=50)),
            ],
            options={
                "db_table": "list_basculas",
                "managed": False,
            },
        ),
    ]
