# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: com/terraquantum/storage/v1alpha1/create_storage_from_external.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from com.terraquantum.storage.v1alpha1 import storage_pb2 as com_dot_terraquantum_dot_storage_dot_v1alpha1_dot_storage__pb2
from buf.validate import validate_pb2 as buf_dot_validate_dot_validate__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\nDcom/terraquantum/storage/v1alpha1/create_storage_from_external.proto\x12!com.terraquantum.storage.v1alpha1\x1a/com/terraquantum/storage/v1alpha1/storage.proto\x1a\x1b\x62uf/validate/validate.proto\"\xf7\x01\n&CreateStorageFromExternalBucketRequest\x12\'\n\nproject_id\x18\x01 \x01(\tB\x08\xbaH\x05r\x03\xb0\x01\x01R\tprojectId\x12\x12\n\x04name\x18\x02 \x01(\tR\x04name\x12 \n\x0b\x64\x65scription\x18\x03 \x01(\tR\x0b\x64\x65scription\x12\x10\n\x03url\x18\x04 \x01(\tR\x03url\x12\\\n\x0bsensitivity\x18\x05 \x01(\x0e\x32:.com.terraquantum.storage.v1alpha1.DatasetSensitivityProtoR\x0bsensitivityB\xc5\x02\n%com.com.terraquantum.storage.v1alpha1B\x1e\x43reateStorageFromExternalProtoP\x01ZUterraquantum.swiss/tq42_grpc_client/com/terraquantum/storage/v1alpha1;storagev1alpha1\xa2\x02\x03\x43TS\xaa\x02!Com.Terraquantum.Storage.V1alpha1\xca\x02!Com\\Terraquantum\\Storage\\V1alpha1\xe2\x02-Com\\Terraquantum\\Storage\\V1alpha1\\GPBMetadata\xea\x02$Com::Terraquantum::Storage::V1alpha1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'com.terraquantum.storage.v1alpha1.create_storage_from_external_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n%com.com.terraquantum.storage.v1alpha1B\036CreateStorageFromExternalProtoP\001ZUterraquantum.swiss/tq42_grpc_client/com/terraquantum/storage/v1alpha1;storagev1alpha1\242\002\003CTS\252\002!Com.Terraquantum.Storage.V1alpha1\312\002!Com\\Terraquantum\\Storage\\V1alpha1\342\002-Com\\Terraquantum\\Storage\\V1alpha1\\GPBMetadata\352\002$Com::Terraquantum::Storage::V1alpha1'
  _globals['_CREATESTORAGEFROMEXTERNALBUCKETREQUEST'].fields_by_name['project_id']._options = None
  _globals['_CREATESTORAGEFROMEXTERNALBUCKETREQUEST'].fields_by_name['project_id']._serialized_options = b'\272H\005r\003\260\001\001'
  _globals['_CREATESTORAGEFROMEXTERNALBUCKETREQUEST']._serialized_start=186
  _globals['_CREATESTORAGEFROMEXTERNALBUCKETREQUEST']._serialized_end=433
# @@protoc_insertion_point(module_scope)
