
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-04-10T12:12:26-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "56f94b4594dbcb2b980731d7065fcfd1f421ba2c",
 "version": "1.22.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
