
# This file was generated by 'versioneer.py' (0.28) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-04-15T00:28:23+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "88a2a1cd4a2dd12791153462ff4ab9a7122be40f",
 "version": "0.3.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
