# coding: utf-8

"""
    SEC Smart API

    This is the API for the <b>SEC Smart System</b>.<br><font color=\"#ff0000\"><b>ACHTUNG:</b> Diese API ist noch nicht für den produktiven Einsatz freigegeben!</font>  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class SettingsSleeptimeBody(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'sleep_time': 'SettingspropertiessleepTime'
    }

    attribute_map = {
        'sleep_time': 'sleepTime'
    }

    def __init__(self, sleep_time=None):  # noqa: E501
        """SettingsSleeptimeBody - a model defined in Swagger"""  # noqa: E501
        self._sleep_time = None
        self.discriminator = None
        if sleep_time is not None:
            self.sleep_time = sleep_time

    @property
    def sleep_time(self):
        """Gets the sleep_time of this SettingsSleeptimeBody.  # noqa: E501


        :return: The sleep_time of this SettingsSleeptimeBody.  # noqa: E501
        :rtype: SettingspropertiessleepTime
        """
        return self._sleep_time

    @sleep_time.setter
    def sleep_time(self, sleep_time):
        """Sets the sleep_time of this SettingsSleeptimeBody.


        :param sleep_time: The sleep_time of this SettingsSleeptimeBody.  # noqa: E501
        :type: SettingspropertiessleepTime
        """

        self._sleep_time = sleep_time

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(SettingsSleeptimeBody, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, SettingsSleeptimeBody):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
