# coding: utf-8

"""
    API pro taxonomii CITES

    Toto je API pro taxonomii CITES  # noqa: E501

    OpenAPI spec version: 1.0.1
    Contact: rjaeger@sysnet.cz
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import taxonomy
from taxonomy.models.error_model import ErrorModel  # noqa: E501
from taxonomy.rest import ApiException


class TestErrorModel(unittest.TestCase):
    """ErrorModel unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testErrorModel(self):
        """Test ErrorModel"""
        model = taxonomy.models.error_model.ErrorModel(code=200, message='Chybová hláška TEST')
        assert model.code == 200, 'Error code should be 200'
        assert 'TEST' in model.message, ('Error message should be TEST')


if __name__ == '__main__':
    unittest.main()
