class DashboardPolicies:
    def can_list(self):
        ...

    def can_view(self):
        ...

    def can_edit(self):
        ...

    def can_create(self):
        ...

    def can_delete(self):
        ...

    def can_export(self):
        ...

    def can_import(self):
        ...

    def can_filter(self):
        ...