# coding: utf-8

"""
    flatastic API Schema

    This schema was generated by the reverse-engineered-apis project with the help of alufers/mitmproxy2swagger and openapitools/openapi-generator. It is not guaranteed to be complete or correct.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from reverse_engineered_apis.flatastic.api.shoppinglist_api import ShoppinglistApi


class TestShoppinglistApi(unittest.TestCase):
    """ShoppinglistApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ShoppinglistApi()

    def tearDown(self) -> None:
        pass

    def test_get_shoppinglist(self) -> None:
        """Test case for get_shoppinglist

        """
        pass

    def test_post_shoppinglist(self) -> None:
        """Test case for post_shoppinglist

        """
        pass


if __name__ == '__main__':
    unittest.main()
