# coding: utf-8

"""
    TMDB API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 3
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from tmdb_client.models.movie_add_rating_request import MovieAddRatingRequest

class TestMovieAddRatingRequest(unittest.TestCase):
    """MovieAddRatingRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> MovieAddRatingRequest:
        """Test MovieAddRatingRequest
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `MovieAddRatingRequest`
        """
        model = MovieAddRatingRequest()
        if include_optional:
            return MovieAddRatingRequest(
                raw_body = ''
            )
        else:
            return MovieAddRatingRequest(
                raw_body = '',
        )
        """

    def testMovieAddRatingRequest(self):
        """Test MovieAddRatingRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
