# coding: utf-8

"""
    TMDB API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 3
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from tmdb_client.models.tv_season_watch_providers200_response import TvSeasonWatchProviders200Response

class TestTvSeasonWatchProviders200Response(unittest.TestCase):
    """TvSeasonWatchProviders200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TvSeasonWatchProviders200Response:
        """Test TvSeasonWatchProviders200Response
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TvSeasonWatchProviders200Response`
        """
        model = TvSeasonWatchProviders200Response()
        if include_optional:
            return TvSeasonWatchProviders200Response(
                id = 3624,
                results = tmdb_client.models.tv_season_watch_providers_200_response_results.tv_season_watch_providers_200_response_results(
                    ae = tmdb_client.models.tv_season_watch_providers_200_response_results_ae.tv_season_watch_providers_200_response_results_AE(
                        link = 'https://www.themoviedb.org/tv/1399-game-of-thrones/season/1/watch?locale=AE', 
                        flatrate = [
                            tmdb_client.models.tv_series_watch_providers_200_response_results_ae_flatrate_inner.tv_series_watch_providers_200_response_results_AE_flatrate_inner(
                                logo_path = '/xEPXbwbfABzPrUTWbgtDFH1NOa.jpg', 
                                provider_id = 629, 
                                provider_name = 'OSN', 
                                display_priority = 11, )
                            ], ), 
                    ar = tmdb_client.models.tv_season_watch_providers_200_response_results_ar.tv_season_watch_providers_200_response_results_AR(
                        link = 'https://www.themoviedb.org/tv/1399-game-of-thrones/season/1/watch?locale=AR', ), 
                    at = tmdb_client.models.tv_season_watch_providers_200_response_results_at.tv_season_watch_providers_200_response_results_AT(
                        link = 'https://www.themoviedb.org/tv/1399-game-of-thrones/season/1/watch?locale=AT', 
                        buy = [
                            tmdb_client.models.movie_watch_providers_200_response_results_at_buy_inner.movie_watch_providers_200_response_results_AT_buy_inner(
                                logo_path = '/5NyLm42TmCqCMOZFvH4fcoSNKEW.jpg', 
                                provider_id = 10, 
                                provider_name = 'Amazon Video', 
                                display_priority = 3, )
                            ], ), 
                    au = tmdb_client.models.tv_season_watch_providers_200_response_results_au.tv_season_watch_providers_200_response_results_AU(
                        link = 'https://www.themoviedb.org/tv/1399-game-of-thrones/season/1/watch?locale=AU', ), 
                    ba = tmdb_client.models.tv_season_watch_providers_200_response_results_ba.tv_season_watch_providers_200_response_results_BA(
                        link = 'https://www.themoviedb.org/tv/1399-game-of-thrones/season/1/watch?locale=BA', ), 
                    bb = tmdb_client.models.tv_season_watch_providers_200_response_results_bb.tv_season_watch_providers_200_response_results_BB(
                        link = 'https://www.themoviedb.org/tv/1399-game-of-thrones/season/1/watch?locale=BB', ), 
                    be = tmdb_client.models.tv_season_watch_providers_200_response_results_be.tv_season_watch_providers_200_response_results_BE(
                        link = 'https://www.themoviedb.org/tv/1399-game-of-thrones/season/1/watch?locale=BE', ), 
                    bg = tmdb_client.models.tv_season_watch_providers_200_response_results_bg.tv_season_watch_providers_200_response_results_BG(
                        link = 'https://www.themoviedb.org/tv/1399-game-of-thrones/season/1/watch?locale=BG', ), 
                    bo = tmdb_client.models.tv_season_watch_providers_200_response_results_bo.tv_season_watch_providers_200_response_results_BO(
                        link = 'https://www.themoviedb.org/tv/1399-game-of-thrones/season/1/watch?locale=BO', ), 
                    br = tmdb_client.models.tv_season_watch_providers_200_response_results_br.tv_season_watch_providers_200_response_results_BR(
                        link = 'https://www.themoviedb.org/tv/1399-game-of-thrones/season/1/watch?locale=BR', ), 
                    bs = tmdb_client.models.tv_season_watch_providers_200_response_results_bs.tv_season_watch_providers_200_response_results_BS(
                        link = 'https://www.themoviedb.org/tv/1399-game-of-thrones/season/1/watch?locale=BS', ), 
                    ca = tmdb_client.models.tv_season_watch_providers_200_response_results_ca.tv_season_watch_providers_200_response_results_CA(
                        link = 'https://www.themoviedb.org/tv/1399-game-of-thrones/season/1/watch?locale=CA', ), 
                    ch = tmdb_client.models.tv_season_watch_providers_200_response_results_ch.tv_season_watch_providers_200_response_results_CH(
                        link = 'https://www.themoviedb.org/tv/1399-game-of-thrones/season/1/watch?locale=CH', ), 
                    ci = tmdb_client.models.tv_season_watch_providers_200_response_results_ci.tv_season_watch_providers_200_response_results_CI(
                        link = 'https://www.themoviedb.org/tv/1399-game-of-thrones/season/1/watch?locale=CI', ), 
                    cl = tmdb_client.models.tv_season_watch_providers_200_response_results_cl.tv_season_watch_providers_200_response_results_CL(
                        link = 'https://www.themoviedb.org/tv/1399-game-of-thrones/season/1/watch?locale=CL', ), 
                    co = tmdb_client.models.tv_season_watch_providers_200_response_results_co.tv_season_watch_providers_200_response_results_CO(
                        link = 'https://www.themoviedb.org/tv/1399-game-of-thrones/season/1/watch?locale=CO', ), 
                    cr = tmdb_client.models.tv_season_watch_providers_200_response_results_cr.tv_season_watch_providers_200_response_results_CR(
                        link = 'https://www.themoviedb.org/tv/1399-game-of-thrones/season/1/watch?locale=CR', ), 
                    cz = tmdb_client.models.tv_season_watch_providers_200_response_results_cz.tv_season_watch_providers_200_response_results_CZ(
                        link = 'https://www.themoviedb.org/tv/1399-game-of-thrones/season/1/watch?locale=CZ', ), 
                    de = tmdb_client.models.tv_season_watch_providers_200_response_results_de.tv_season_watch_providers_200_response_results_DE(
                        link = 'https://www.themoviedb.org/tv/1399-game-of-thrones/season/1/watch?locale=DE', ), 
                    dk = tmdb_client.models.tv_season_watch_providers_200_response_results_dk.tv_season_watch_providers_200_response_results_DK(
                        link = 'https://www.themoviedb.org/tv/1399-game-of-thrones/season/1/watch?locale=DK', ), 
                    do = tmdb_client.models.tv_season_watch_providers_200_response_results_do.tv_season_watch_providers_200_response_results_DO(
                        link = 'https://www.themoviedb.org/tv/1399-game-of-thrones/season/1/watch?locale=DO', ), 
                    dz = tmdb_client.models.tv_season_watch_providers_200_response_results_dz.tv_season_watch_providers_200_response_results_DZ(
                        link = 'https://www.themoviedb.org/tv/1399-game-of-thrones/season/1/watch?locale=DZ', ), 
                    ec = tmdb_client.models.tv_season_watch_providers_200_response_results_ec.tv_season_watch_providers_200_response_results_EC(
                        link = 'https://www.themoviedb.org/tv/1399-game-of-thrones/season/1/watch?locale=EC', ), 
                    eg = tmdb_client.models.tv_season_watch_providers_200_response_results_eg.tv_season_watch_providers_200_response_results_EG(
                        link = 'https://www.themoviedb.org/tv/1399-game-of-thrones/season/1/watch?locale=EG', ), 
                    es = tmdb_client.models.tv_season_watch_providers_200_response_results_es.tv_season_watch_providers_200_response_results_ES(
                        link = 'https://www.themoviedb.org/tv/1399-game-of-thrones/season/1/watch?locale=ES', ), 
                    fi = tmdb_client.models.tv_season_watch_providers_200_response_results_fi.tv_season_watch_providers_200_response_results_FI(
                        link = 'https://www.themoviedb.org/tv/1399-game-of-thrones/season/1/watch?locale=FI', ), 
                    fr = tmdb_client.models.tv_season_watch_providers_200_response_results_fr.tv_season_watch_providers_200_response_results_FR(
                        link = 'https://www.themoviedb.org/tv/1399-game-of-thrones/season/1/watch?locale=FR', ), 
                    gb = tmdb_client.models.tv_season_watch_providers_200_response_results_gb.tv_season_watch_providers_200_response_results_GB(
                        link = 'https://www.themoviedb.org/tv/1399-game-of-thrones/season/1/watch?locale=GB', ), 
                    gf = tmdb_client.models.tv_season_watch_providers_200_response_results_gf.tv_season_watch_providers_200_response_results_GF(
                        link = 'https://www.themoviedb.org/tv/1399-game-of-thrones/season/1/watch?locale=GF', ), 
                    gh = tmdb_client.models.tv_season_watch_providers_200_response_results_gh.tv_season_watch_providers_200_response_results_GH(
                        link = 'https://www.themoviedb.org/tv/1399-game-of-thrones/season/1/watch?locale=GH', ), 
                    gq = tmdb_client.models.tv_season_watch_providers_200_response_results_gq.tv_season_watch_providers_200_response_results_GQ(
                        link = 'https://www.themoviedb.org/tv/1399-game-of-thrones/season/1/watch?locale=GQ', ), 
                    gt = tmdb_client.models.tv_season_watch_providers_200_response_results_gt.tv_season_watch_providers_200_response_results_GT(
                        link = 'https://www.themoviedb.org/tv/1399-game-of-thrones/season/1/watch?locale=GT', ), 
                    hk = tmdb_client.models.tv_season_watch_providers_200_response_results_hk.tv_season_watch_providers_200_response_results_HK(
                        link = 'https://www.themoviedb.org/tv/1399-game-of-thrones/season/1/watch?locale=HK', ), 
                    hn = tmdb_client.models.tv_season_watch_providers_200_response_results_hn.tv_season_watch_providers_200_response_results_HN(
                        link = 'https://www.themoviedb.org/tv/1399-game-of-thrones/season/1/watch?locale=HN', ), 
                    hr = tmdb_client.models.tv_season_watch_providers_200_response_results_hr.tv_season_watch_providers_200_response_results_HR(
                        link = 'https://www.themoviedb.org/tv/1399-game-of-thrones/season/1/watch?locale=HR', ), 
                    hu = tmdb_client.models.tv_season_watch_providers_200_response_results_hu.tv_season_watch_providers_200_response_results_HU(
                        link = 'https://www.themoviedb.org/tv/1399-game-of-thrones/season/1/watch?locale=HU', ), 
                    id = tmdb_client.models.tv_season_watch_providers_200_response_results_id.tv_season_watch_providers_200_response_results_ID(
                        link = 'https://www.themoviedb.org/tv/1399-game-of-thrones/season/1/watch?locale=ID', ), 
                    ie = tmdb_client.models.tv_season_watch_providers_200_response_results_ie.tv_season_watch_providers_200_response_results_IE(
                        link = 'https://www.themoviedb.org/tv/1399-game-of-thrones/season/1/watch?locale=IE', ), 
                    il = tmdb_client.models.tv_season_watch_providers_200_response_results_il.tv_season_watch_providers_200_response_results_IL(
                        link = 'https://www.themoviedb.org/tv/1399-game-of-thrones/season/1/watch?locale=IL', ), 
                    iq = tmdb_client.models.tv_season_watch_providers_200_response_results_iq.tv_season_watch_providers_200_response_results_IQ(
                        link = 'https://www.themoviedb.org/tv/1399-game-of-thrones/season/1/watch?locale=IQ', ), 
                    it = tmdb_client.models.tv_season_watch_providers_200_response_results_it.tv_season_watch_providers_200_response_results_IT(
                        link = 'https://www.themoviedb.org/tv/1399-game-of-thrones/season/1/watch?locale=IT', ), 
                    jm = tmdb_client.models.tv_season_watch_providers_200_response_results_jm.tv_season_watch_providers_200_response_results_JM(
                        link = 'https://www.themoviedb.org/tv/1399-game-of-thrones/season/1/watch?locale=JM', ), 
                    jp = tmdb_client.models.tv_season_watch_providers_200_response_results_jp.tv_season_watch_providers_200_response_results_JP(
                        link = 'https://www.themoviedb.org/tv/1399-game-of-thrones/season/1/watch?locale=JP', 
                        rent = [
                            tmdb_client.models.tv_series_watch_providers_200_response_results_jp_buy_inner.tv_series_watch_providers_200_response_results_JP_buy_inner(
                                logo_path = '/5NyLm42TmCqCMOZFvH4fcoSNKEW.jpg', 
                                provider_id = 10, 
                                provider_name = 'Amazon Video', 
                                display_priority = 6, )
                            ], ), 
                    ke = tmdb_client.models.tv_season_watch_providers_200_response_results_ke.tv_season_watch_providers_200_response_results_KE(
                        link = 'https://www.themoviedb.org/tv/1399-game-of-thrones/season/1/watch?locale=KE', ), 
                    kr = tmdb_client.models.tv_season_watch_providers_200_response_results_kr.tv_season_watch_providers_200_response_results_KR(
                        link = 'https://www.themoviedb.org/tv/1399-game-of-thrones/season/1/watch?locale=KR', ), 
                    lb = tmdb_client.models.tv_season_watch_providers_200_response_results_lb.tv_season_watch_providers_200_response_results_LB(
                        link = 'https://www.themoviedb.org/tv/1399-game-of-thrones/season/1/watch?locale=LB', ), 
                    ly = tmdb_client.models.tv_season_watch_providers_200_response_results_ly.tv_season_watch_providers_200_response_results_LY(
                        link = 'https://www.themoviedb.org/tv/1399-game-of-thrones/season/1/watch?locale=LY', ), 
                    md = tmdb_client.models.tv_season_watch_providers_200_response_results_md.tv_season_watch_providers_200_response_results_MD(
                        link = 'https://www.themoviedb.org/tv/1399-game-of-thrones/season/1/watch?locale=MD', ), 
                    mk = tmdb_client.models.tv_season_watch_providers_200_response_results_mk.tv_season_watch_providers_200_response_results_MK(
                        link = 'https://www.themoviedb.org/tv/1399-game-of-thrones/season/1/watch?locale=MK', ), 
                    mu = tmdb_client.models.tv_season_watch_providers_200_response_results_mu.tv_season_watch_providers_200_response_results_MU(
                        link = 'https://www.themoviedb.org/tv/1399-game-of-thrones/season/1/watch?locale=MU', ), 
                    mx = tmdb_client.models.tv_season_watch_providers_200_response_results_mx.tv_season_watch_providers_200_response_results_MX(
                        link = 'https://www.themoviedb.org/tv/1399-game-of-thrones/season/1/watch?locale=MX', ), 
                    my = tmdb_client.models.tv_season_watch_providers_200_response_results_my.tv_season_watch_providers_200_response_results_MY(
                        link = 'https://www.themoviedb.org/tv/1399-game-of-thrones/season/1/watch?locale=MY', ), 
                    mz = tmdb_client.models.tv_season_watch_providers_200_response_results_mz.tv_season_watch_providers_200_response_results_MZ(
                        link = 'https://www.themoviedb.org/tv/1399-game-of-thrones/season/1/watch?locale=MZ', ), 
                    ne = tmdb_client.models.tv_season_watch_providers_200_response_results_ne.tv_season_watch_providers_200_response_results_NE(
                        link = 'https://www.themoviedb.org/tv/1399-game-of-thrones/season/1/watch?locale=NE', ), 
                    ng = tmdb_client.models.tv_season_watch_providers_200_response_results_ng.tv_season_watch_providers_200_response_results_NG(
                        link = 'https://www.themoviedb.org/tv/1399-game-of-thrones/season/1/watch?locale=NG', ), 
                    nl = tmdb_client.models.tv_season_watch_providers_200_response_results_nl.tv_season_watch_providers_200_response_results_NL(
                        link = 'https://www.themoviedb.org/tv/1399-game-of-thrones/season/1/watch?locale=NL', ), 
                    no = tmdb_client.models.tv_season_watch_providers_200_response_results_no.tv_season_watch_providers_200_response_results_NO(
                        link = 'https://www.themoviedb.org/tv/1399-game-of-thrones/season/1/watch?locale=NO', ), 
                    nz = tmdb_client.models.tv_season_watch_providers_200_response_results_nz.tv_season_watch_providers_200_response_results_NZ(
                        link = 'https://www.themoviedb.org/tv/1399-game-of-thrones/season/1/watch?locale=NZ', ), 
                    pa = tmdb_client.models.tv_season_watch_providers_200_response_results_pa.tv_season_watch_providers_200_response_results_PA(
                        link = 'https://www.themoviedb.org/tv/1399-game-of-thrones/season/1/watch?locale=PA', ), 
                    pe = tmdb_client.models.tv_season_watch_providers_200_response_results_pe.tv_season_watch_providers_200_response_results_PE(
                        link = 'https://www.themoviedb.org/tv/1399-game-of-thrones/season/1/watch?locale=PE', ), 
                    ph = tmdb_client.models.tv_season_watch_providers_200_response_results_ph.tv_season_watch_providers_200_response_results_PH(
                        link = 'https://www.themoviedb.org/tv/1399-game-of-thrones/season/1/watch?locale=PH', ), 
                    pl = tmdb_client.models.tv_season_watch_providers_200_response_results_pl.tv_season_watch_providers_200_response_results_PL(
                        link = 'https://www.themoviedb.org/tv/1399-game-of-thrones/season/1/watch?locale=PL', ), 
                    ps = tmdb_client.models.tv_season_watch_providers_200_response_results_ps.tv_season_watch_providers_200_response_results_PS(
                        link = 'https://www.themoviedb.org/tv/1399-game-of-thrones/season/1/watch?locale=PS', ), 
                    pt = tmdb_client.models.tv_season_watch_providers_200_response_results_pt.tv_season_watch_providers_200_response_results_PT(
                        link = 'https://www.themoviedb.org/tv/1399-game-of-thrones/season/1/watch?locale=PT', ), 
                    py = tmdb_client.models.tv_season_watch_providers_200_response_results_py.tv_season_watch_providers_200_response_results_PY(
                        link = 'https://www.themoviedb.org/tv/1399-game-of-thrones/season/1/watch?locale=PY', ), 
                    ro = tmdb_client.models.tv_season_watch_providers_200_response_results_ro.tv_season_watch_providers_200_response_results_RO(
                        link = 'https://www.themoviedb.org/tv/1399-game-of-thrones/season/1/watch?locale=RO', ), 
                    rs = tmdb_client.models.tv_season_watch_providers_200_response_results_rs.tv_season_watch_providers_200_response_results_RS(
                        link = 'https://www.themoviedb.org/tv/1399-game-of-thrones/season/1/watch?locale=RS', ), 
                    ru = tmdb_client.models.tv_season_watch_providers_200_response_results_ru.tv_season_watch_providers_200_response_results_RU(
                        link = 'https://www.themoviedb.org/tv/1399-game-of-thrones/season/1/watch?locale=RU', ), 
                    sa = tmdb_client.models.tv_season_watch_providers_200_response_results_sa.tv_season_watch_providers_200_response_results_SA(
                        link = 'https://www.themoviedb.org/tv/1399-game-of-thrones/season/1/watch?locale=SA', ), 
                    sc = tmdb_client.models.tv_season_watch_providers_200_response_results_sc.tv_season_watch_providers_200_response_results_SC(
                        link = 'https://www.themoviedb.org/tv/1399-game-of-thrones/season/1/watch?locale=SC', ), 
                    se = tmdb_client.models.tv_season_watch_providers_200_response_results_se.tv_season_watch_providers_200_response_results_SE(
                        link = 'https://www.themoviedb.org/tv/1399-game-of-thrones/season/1/watch?locale=SE', ), 
                    sg = tmdb_client.models.tv_season_watch_providers_200_response_results_sg.tv_season_watch_providers_200_response_results_SG(
                        link = 'https://www.themoviedb.org/tv/1399-game-of-thrones/season/1/watch?locale=SG', ), 
                    si = tmdb_client.models.tv_season_watch_providers_200_response_results_si.tv_season_watch_providers_200_response_results_SI(
                        link = 'https://www.themoviedb.org/tv/1399-game-of-thrones/season/1/watch?locale=SI', ), 
                    sk = tmdb_client.models.tv_season_watch_providers_200_response_results_sk.tv_season_watch_providers_200_response_results_SK(
                        link = 'https://www.themoviedb.org/tv/1399-game-of-thrones/season/1/watch?locale=SK', ), 
                    sn = tmdb_client.models.tv_season_watch_providers_200_response_results_sn.tv_season_watch_providers_200_response_results_SN(
                        link = 'https://www.themoviedb.org/tv/1399-game-of-thrones/season/1/watch?locale=SN', ), 
                    sv = tmdb_client.models.tv_season_watch_providers_200_response_results_sv.tv_season_watch_providers_200_response_results_SV(
                        link = 'https://www.themoviedb.org/tv/1399-game-of-thrones/season/1/watch?locale=SV', ), 
                    th = tmdb_client.models.tv_season_watch_providers_200_response_results_th.tv_season_watch_providers_200_response_results_TH(
                        link = 'https://www.themoviedb.org/tv/1399-game-of-thrones/season/1/watch?locale=TH', ), 
                    tr = tmdb_client.models.tv_season_watch_providers_200_response_results_tr.tv_season_watch_providers_200_response_results_TR(
                        link = 'https://www.themoviedb.org/tv/1399-game-of-thrones/season/1/watch?locale=TR', ), 
                    tt = tmdb_client.models.tv_season_watch_providers_200_response_results_tt.tv_season_watch_providers_200_response_results_TT(
                        link = 'https://www.themoviedb.org/tv/1399-game-of-thrones/season/1/watch?locale=TT', ), 
                    tw = tmdb_client.models.tv_season_watch_providers_200_response_results_tw.tv_season_watch_providers_200_response_results_TW(
                        link = 'https://www.themoviedb.org/tv/1399-game-of-thrones/season/1/watch?locale=TW', ), 
                    tz = tmdb_client.models.tv_season_watch_providers_200_response_results_tz.tv_season_watch_providers_200_response_results_TZ(
                        link = 'https://www.themoviedb.org/tv/1399-game-of-thrones/season/1/watch?locale=TZ', ), 
                    ug = tmdb_client.models.tv_season_watch_providers_200_response_results_ug.tv_season_watch_providers_200_response_results_UG(
                        link = 'https://www.themoviedb.org/tv/1399-game-of-thrones/season/1/watch?locale=UG', ), 
                    us = tmdb_client.models.tv_season_watch_providers_200_response_results_us.tv_season_watch_providers_200_response_results_US(
                        link = 'https://www.themoviedb.org/tv/1399-game-of-thrones/season/1/watch?locale=US', 
                        free = [
                            tmdb_client.models.tv_series_watch_providers_200_response_results_br_flatrate_inner.tv_series_watch_providers_200_response_results_BR_flatrate_inner(
                                logo_path = '/Ajqyt5aNxNGjmF9uOfxArGrdf3X.jpg', 
                                provider_id = 384, 
                                provider_name = 'HBO Max', 
                                display_priority = 7, )
                            ], ), 
                    uy = tmdb_client.models.tv_season_watch_providers_200_response_results_uy.tv_season_watch_providers_200_response_results_UY(
                        link = 'https://www.themoviedb.org/tv/1399-game-of-thrones/season/1/watch?locale=UY', ), 
                    ve = tmdb_client.models.tv_season_watch_providers_200_response_results_ve.tv_season_watch_providers_200_response_results_VE(
                        link = 'https://www.themoviedb.org/tv/1399-game-of-thrones/season/1/watch?locale=VE', ), 
                    za = tmdb_client.models.tv_season_watch_providers_200_response_results_za.tv_season_watch_providers_200_response_results_ZA(
                        link = 'https://www.themoviedb.org/tv/1399-game-of-thrones/season/1/watch?locale=ZA', ), 
                    zm = tmdb_client.models.tv_season_watch_providers_200_response_results_zm.tv_season_watch_providers_200_response_results_ZM(
                        link = 'https://www.themoviedb.org/tv/1399-game-of-thrones/season/1/watch?locale=ZM', ), )
            )
        else:
            return TvSeasonWatchProviders200Response(
        )
        """

    def testTvSeasonWatchProviders200Response(self):
        """Test TvSeasonWatchProviders200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
