
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-04-10T22:00:16-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "b1c7bf3bac3bac87567c901492831fa36bbaf546",
 "version": "2.3.11"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
