from dataclasses import dataclass

@dataclass
class Message:
    role: str
    content: str
    name: str | None = ...
    def __eq__(self, other: object): ...
    def __init__(self, role, content, name) -> None: ...

@dataclass
class StructuredPrompt:
    name: str
    system_message: str
    conversation: list[Message]
    def __eq__(self, other: object): ...
    @classmethod
    def from_promptdown_string(cls, promptdown_string: str): ...
    @classmethod
    def from_promptdown_file(cls, file_path: str): ...
    def to_promptdown_string(self) -> str: ...
    def to_promptdown_file(self, file_path: str): ...
    def __init__(self, name, system_message, conversation) -> None: ...
