
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-04-11T17:16:36-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "de29018103fb136484d0567210d17720e18b37d3",
 "version": "2.10.0.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
