# coding: utf-8

"""
    OpenClientCoolAutomationAPI

    Cool platform REST API  # noqa: E501

    OpenAPI spec version: 2.0.1
    Contact: none@gmail.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class UnitControlSetpointsBody(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'setpoint': 'int'
    }

    attribute_map = {
        'setpoint': 'setpoint'
    }

    def __init__(self, setpoint=None):  # noqa: E501
        """UnitControlSetpointsBody - a model defined in Swagger"""  # noqa: E501
        self._setpoint = None
        self.discriminator = None
        self.setpoint = setpoint

    @property
    def setpoint(self):
        """Gets the setpoint of this UnitControlSetpointsBody.  # noqa: E501

        requested temperature on the same scale the acting user is configured to work with  # noqa: E501

        :return: The setpoint of this UnitControlSetpointsBody.  # noqa: E501
        :rtype: int
        """
        return self._setpoint

    @setpoint.setter
    def setpoint(self, setpoint):
        """Sets the setpoint of this UnitControlSetpointsBody.

        requested temperature on the same scale the acting user is configured to work with  # noqa: E501

        :param setpoint: The setpoint of this UnitControlSetpointsBody.  # noqa: E501
        :type: int
        """
        if setpoint is None:
            raise ValueError("Invalid value for `setpoint`, must not be `None`")  # noqa: E501

        self._setpoint = setpoint

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(UnitControlSetpointsBody, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, UnitControlSetpointsBody):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
