from .main import STRING_CARACTERES_ESPECIAIS_PADRAO,CARACTERES_NORMAIS
from .main import LISTA_STOPWORDS_PADRAO_FREQUENCIA,LISTA_STOPWORDS_PADRAO_TOKENIZACAO,LISTA_PONTOS_FINAIS_PADRAO_FRASES,DICIONARIO_CONFIG_PADRAO_TOKENIZACAO
from .main import DIGITO_DIA,DIGITO_MES,DIGITO_ANO,PADRAO_REGEX_DATA
from .main import DDD_PAIS, DDD_ESTADO, DDD_CELULAR, PADRAO_REGEX_TELEFONE_CELULAR
from .main import PADRAO_REGEX_EMAIL,PADRAO_REGEX_LINKS, PADRAO_REGEX_NUMEROS,PADRAO_REGEX_DINHEIRO,PADRAO_REGEX_CPF,PADRAO_REGEX_CEP,PADRAO_REGEX_RG
from .main import padronizarRG,padronizarCPF,padronizarCEP,padronizarDatas,padronizarDinheiros,padronizarEmails,padronizarLinks,padronizarNumeros,normalizarTexto,padronizarTelefoneCelular,padronizarTextoParaMinuscula
from .main import coletarTextoDeArquivoTxt,removerCaracteresEspeciais,removerCaracteresEstranhos,removerEspacosEmBrancoExtras,transformarTextoSubstituindoCaracteres,verificarExistenciaDeElemento,contarFrequenciaDePalavras,formatarTexto,tokenizarTexto,organizaTextoPelasLinhas
