# Generated by Django 2.2 on 2023-01-30 07:43

from django.conf import settings
from django.db import migrations
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
        ("events", "0004_auto_20220509_0816"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="hero_image",
            field=filer.fields.image.FilerImageField(
                blank=True,
                help_text="Select an image that will be displayed as the hero for the event detail page. ",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.FILER_IMAGE_MODEL,
            ),
        ),
    ]
