LENS2_BASE_URL = "LENS2_BASE_URL"
LENS2_NAME = "LENS2_NAME"
LENS2_META_PATH = "LENS2_META_PATH"

DATAOS_USER_NAME = "DATAOS_USER_NAME"
DATAOS_USER_APIKEY = "DATAOS_USER_APIKEY"

LENS2_BOARD_PATH = "LENS2_BOARD_PATH"
LENS2_CHECKS_PATH = "LENS2_CHECKS_PATH"
