LENS2_BASE_URL = "LENS2_BASE_URL"
LENS2_NAME = "LENS2_NAME"
LENS2_META_PATH = "LENS2_META_PATH"

LENS2_DATAOS_USER_NAME = "LENS2_DATAOS_USER_NAME"
LENS2_DATAOS_USER_APIKEY = "LENS2_DATAOS_USER_APIKEY"

LENS2_RILL_PATH = "LENS2_RILL_PATH"
LENS2_CHECKS_PATH = "LENS2_CHECKS_PATH"
