
# This file was generated by 'versioneer.py' (0.28) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-04-10T12:48:30+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "a450bb708bfe83622c0c0f352793e7093529cf08",
 "version": "0.8.5"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
