PLATFORM_API_KEY_NAME = "SCALIFI_AI_API_KEY"

CREDENTIALS_AUTH_METHOD_API_KEY_KEY = "api_key"
AUTH_API_KEY_HEADER_NAME = "x-scf-api-key"

PLATFORM_URL_BASE_SLUG = "http://127.0.0.1:8010"
PLATFORM_URL_NAME = "SCALIFI_AI_PLATFORM_URL"
LIBRARY_BASE_DIR_NAME = ".scalifiai"
REQUEST_NAMAGER_VERIFY_SSL_NAME = "SCALIFI_AI_REQUESTS_VERIFY_SSL"
REQUEST_NAMAGER_ALLOW_RESPONSE_REDIRECTS_NAME = (
    "SCALIFI_AI_REQUESTS_ALLOW_RESPONSE_REDIRECTS"
)
