# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from kerfed.protos.api.v1 import cam_pb2 as kerfed_dot_protos_dot_api_dot_v1_dot_cam__pb2


class CAMServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Pack = channel.unary_unary(
                '/kerfed.protos.api.v1.CAMService/Pack',
                request_serializer=kerfed_dot_protos_dot_api_dot_v1_dot_cam__pb2.PackRequest.SerializeToString,
                response_deserializer=kerfed_dot_protos_dot_api_dot_v1_dot_cam__pb2.PackResponse.FromString,
                )


class CAMServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Pack(self, request, context):
        """Pack flat parts onto a sheet.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CAMServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Pack': grpc.unary_unary_rpc_method_handler(
                    servicer.Pack,
                    request_deserializer=kerfed_dot_protos_dot_api_dot_v1_dot_cam__pb2.PackRequest.FromString,
                    response_serializer=kerfed_dot_protos_dot_api_dot_v1_dot_cam__pb2.PackResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'kerfed.protos.api.v1.CAMService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class CAMService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Pack(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/kerfed.protos.api.v1.CAMService/Pack',
            kerfed_dot_protos_dot_api_dot_v1_dot_cam__pb2.PackRequest.SerializeToString,
            kerfed_dot_protos_dot_api_dot_v1_dot_cam__pb2.PackResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
