# coding: utf-8

"""
    flatastic API Schema

    This schema was generated by the reverse-engineered-apis project with the help of alufers/mitmproxy2swagger and openapitools/openapi-generator. It is not guaranteed to be complete or correct.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from reverse_engineered_apis.flatastic.models.get_cashflow200_response_inner_items_inner_cost_allocation_inner import GetCashflow200ResponseInnerItemsInnerCostAllocationInner

class TestGetCashflow200ResponseInnerItemsInnerCostAllocationInner(unittest.TestCase):
    """GetCashflow200ResponseInnerItemsInnerCostAllocationInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetCashflow200ResponseInnerItemsInnerCostAllocationInner:
        """Test GetCashflow200ResponseInnerItemsInnerCostAllocationInner
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetCashflow200ResponseInnerItemsInnerCostAllocationInner`
        """
        model = GetCashflow200ResponseInnerItemsInnerCostAllocationInner()
        if include_optional:
            return GetCashflow200ResponseInnerItemsInnerCostAllocationInner(
                user_id = 1.337,
                amount = 1.337
            )
        else:
            return GetCashflow200ResponseInnerItemsInnerCostAllocationInner(
        )
        """

    def testGetCashflow200ResponseInnerItemsInnerCostAllocationInner(self):
        """Test GetCashflow200ResponseInnerItemsInnerCostAllocationInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
