# coding: utf-8

"""
    flatastic API Schema

    This schema was generated by the reverse-engineered-apis project with the help of alufers/mitmproxy2swagger and openapitools/openapi-generator. It is not guaranteed to be complete or correct.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from reverse_engineered_apis.flatastic.models.post_image200_response_wg_image import PostImage200ResponseWgImage

class TestPostImage200ResponseWgImage(unittest.TestCase):
    """PostImage200ResponseWgImage unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PostImage200ResponseWgImage:
        """Test PostImage200ResponseWgImage
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PostImage200ResponseWgImage`
        """
        model = PostImage200ResponseWgImage()
        if include_optional:
            return PostImage200ResponseWgImage(
                bucket = '',
                uri = '',
                privacy = '',
                full_s3_url = '',
                file_name = ''
            )
        else:
            return PostImage200ResponseWgImage(
        )
        """

    def testPostImage200ResponseWgImage(self):
        """Test PostImage200ResponseWgImage"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
