# coding: utf-8

"""
    API pro taxonomii CITES

    Toto je API pro taxonomii CITES  # noqa: E501

    OpenAPI spec version: 1.0.1
    Contact: rjaeger@sysnet.cz
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import taxonomy
from taxonomy.models.taxon_entry_type import TaxonEntryType  # noqa: E501
from taxonomy.rest import ApiException


class TestTaxonEntryType(unittest.TestCase):
    """TaxonEntryType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTaxonEntryType(self):
        """Test TaxonEntryType"""
        model = taxonomy.models.taxon_entry_type.TaxonEntryType(name_scientific='Nepenthes veitchii')
        assert model is not None


if __name__ == '__main__':
    unittest.main()
