# coding: utf-8

"""
    API pro taxonomii CITES

    Toto je API pro taxonomii CITES  # noqa: E501

    OpenAPI spec version: 1.0.1
    Contact: rjaeger@sysnet.cz
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import taxonomy
from taxonomy.models.taxon_entry_list_type import TaxonEntryListType  # noqa: E501
from taxonomy.rest import ApiException


class TestTaxonEntryListType(unittest.TestCase):
    """TaxonEntryListType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTaxonEntryListType(self):
        """Test TaxonEntryListType"""
        model = taxonomy.models.taxon_entry_list_type.TaxonEntryListType()
        assert model is not None
        pass


if __name__ == '__main__':
    unittest.main()
