
# DO NOT EDIT THIS FILE -- AUTOGENERATED BY PANTS
# Target: src/python/arcor2_yumi:arcor2_yumi_dist

from setuptools import setup

setup(**{
    'author': 'Robo@FIT',
    'author_email': 'imaterna@fit.vut.cz',
    'classifiers': [
        'Development Status :: 3 - Alpha',
        'Intended Audience :: Developers',
        'Topic :: Software Development :: Build Tools',
        'License :: OSI Approved :: GNU Lesser General Public License v3 (LGPLv3)',
        'Programming Language :: Python :: 3.11',
        'Natural Language :: English',
        'Topic :: Scientific/Engineering',
    ],
    'description': 'ARCOR2 Calibration',
    'entry_points': {
        'console_scripts': [
            'arcor2_calibration = arcor2_calibration.scripts.calibration:main',
        ],
    },
    'install_requires': (
        'arcor2_calibration_data~=1.1.0',
        'arcor2_calibration~=1.2.0',
        'arcor2~=1.3.0',
    ),
    'license': 'LGPL',
    'long_description': """### ARCOR2 YuMi Demo

Based on [galou/yumipy](https://github.com/galou/yumipy/tree/robotware6_06/yumipy), with a stripped-of support for ROS, adapted to Python 3.8, with added type annotations, etc. The URDF model comes from [OrebroUniversity/yumi](https://github.com/OrebroUniversity/yumi/tree/master/yumi_description) repository.

Tested with RobotWare 6.12.02 and SmartGripper 3.56.

### Functionality

### Limitations

### Ideas for further development / improvements:
- Use `POST /rw/rapid/modules/MainModule?task=T_ROB1&action=set-module-text` to update RAPID during initialization.
  - It would be necessary to somehow assign files on the project service (RAPID) to the ObjectType.
# Changelog

The format is based on [Keep a Changelog](https://keepachangelog.com/en/1.0.0/),

## [0.3.0] - 2024-04-11

### Changed

- Updated dependencies, switched to Python 3.11.

## [0.2.0] - 2022-10-28

### Changed

- Switched to Python 3.10, updated dependencies.

## [0.1.0] - 2021-10-25

### Changed
- The first working version with basic functionality.""",
    'long_description_content_type': 'text/markdown',
    'name': 'arcor2_yumi',
    'namespace_packages': (
    ),
    'package_data': {
        'arcor2_yumi': (
            'VERSION',
            'py.typed',
        ),
    },
    'packages': (
        'arcor2_yumi',
    ),
    'python_requires': '==3.11.*',
    'version': '0.3.0',
})
