from enum import Enum

class App(Enum):
    ASANA = "asana"
    TRELLO = "trello"
    LINEAR = "linear"
    GOOGLE = "google"
    GMAIL = "gmail"
    TIMELY = "timely"
    BOX = "box"
    JIRA = "jira"
    MONDAY = "monday"
    GOOGLE_SHEETS = "google-sheets"
    ATTIO = "attio"
    SHOPIFY = "shopify"
    SLACK = "slack"
    BITBUCKET = "bitbucket"
    GOOGLE_DOCS = "google-docs"
    EVENTBRITE = "eventbrite"
    MAILCHIMP = "mailchimp"
    STRAVA = "strava"
    DROPBOX = "dropbox"
    PAGERDUTY = "pagerduty"
    FIGMA = "figma"
    CLICKUP = "clickup"
    MIRO = "miro"
    GUMROAD = "gumroad"
    KLAVIYO = "klaviyo"
    FRESHDESK = "freshdesk"
    MIXPANEL = "mixpanel"
    INTERCOM = "intercom"
    STACK_EXCHANGE = "stack-exchange"
    ZOOM = "zoom"
    ZOHO = "zoho"
    SPLITWISE = "splitwise"
    NOTION = "notion"
    TASKADE = "taskade"
    TYPEFORM = "typeform"
    PIPEDRIVE = "pipedrive"
    TWITTER = "twitter"
    BOLDSIGN = "boldsign"
    KEAP = "keap"
    AMAZON = "amazon"
    SALESFORCE = "salesforce"
    ZOHO_BOOKS = "zoho_books"
    GORGIAS = "gorgias"
    HACKERRANK_WORK = "hackerrank-work"
    REDDIT = "reddit"
    SERVICEM8 = "servicem8"
    SHORTCUT = "shortcut"
    FRONT = "front"
    SURVEY_MONKEY = "survey-monkey"
    WAKATIME = "wakatime"
    ZOHO_INVENTORY = "zoho_inventory"
    DISCORD = "discord"
    TWITCH = "twitch"
    ATLASSIAN = "atlassian"
    HARVEST = "harvest"
    CALENDLY = "calendly"
    GOOGLE_CALENDAR = "google_calendar"
    BAMBOOHR = "bamboohr"
    GITHUB = "github"
    DEEL = "deel"
    GITLAB = "gitlab"
    HUBSPOT = "hubspot"
    SLACKBOT = "slackbot"
    YANDEX = "yandex"
    BRAINTREE = "braintree"
    ZOHO_INVOICE = "zoho_invoice"
    FRESHBOOKS = "freshbooks"
    AUTH0 = "auth0"
    ONE_DRIVE = "one-drive"
    OKTA = "okta"
    ZOHO_DESK = "zoho_desk"
    SMARTRECRUITERS = "smartrecruiters"
    FACEBOOK = "facebook"
    MURAL = "mural"
    WORKABLE = "workable"
    YOUTUBE = "youtube"
    ADOBE = "adobe"
    SQUARE = "square"
    ASHBY = "ashby"
    HIGHLEVEL = "highlevel"
    GOOGLE_DRIVE = "google-drive"
    EPIC_GAMES = "epic-games"
    TODOIST = "todoist"
    ZOHO_BIGIN = "zoho_bigin"
    AMPLITUDE = "amplitude"
    HEROKU = "heroku"
    SAGE = "sage"
    WAVE_ACCOUNTING = "wave-accounting"
    CLOSE = "close"
    PANDADOC = "pandadoc"
    BLACKBAUD = "blackbaud"
    GURU = "guru"
    SERPAPI = "serpapi"
    SMUGMUG = "smugmug"
    BATTLENET = "battlenet"
    LINKHUT = "linkhut"
    XERO = "xero"
    APIFY = "apify"
    LINEARSANDBOX = "linearsandbox"
    ZENDESK = "zendesk"
    ZOHO_MAIL = "zoho_mail"
    RING_CENTRAL = "ring-central"
    CODEINTERPRETER = "CodeInterpreter"
    GOOGLECALENDAR = "googlecalendar"
    ACCELO = "accelo"

class TestIntegration(Enum):
    ASANA = "test-asana-connector"
    TRELLO = "test-trello-connector"
    LINEAR = "test-linear-connector"
    GOOGLE = "test-google-connector"
    GMAIL = "test-gmail-connector"
    TIMELY = "test-timely-connector"
    BOX = "test-box-connector"
    JIRA = "test-jira-connector"
    MONDAY = "test-monday-connector"
    GOOGLE_SHEETS = "test-google-sheets-connector"
    ATTIO = "test-attio-connector"
    SHOPIFY = "test-shopify-connector"
    SLACK = "test-slack-connector"
    BITBUCKET = "test-bitbucket-connector"
    GOOGLE_DOCS = "test-google-docs-connector"
    EVENTBRITE = "test-eventbrite-connector"
    MAILCHIMP = "test-mailchimp-connector"
    STRAVA = "test-strava-connector"
    DROPBOX = "test-dropbox-connector"
    PAGERDUTY = "test-pagerduty-connector"
    FIGMA = "test-figma-connector"
    CLICKUP = "test-clickup-connector"
    MIRO = "test-miro-connector"
    GUMROAD = "test-gumroad-connector"
    KLAVIYO = "test-klaviyo-connector"
    FRESHDESK = "test-freshdesk-connector"
    MIXPANEL = "test-mixpanel-connector"
    INTERCOM = "test-intercom-connector"
    STACK_EXCHANGE = "test-stack-exchange-connector"
    ZOOM = "test-zoom-connector"
    ZOHO = "test-zoho-connector"
    SPLITWISE = "test-splitwise-connector"
    NOTION = "test-notion-connector"
    TASKADE = "test-taskade-connector"
    TYPEFORM = "test-typeform-connector"
    PIPEDRIVE = "test-pipedrive-connector"
    TWITTER = "test-twitter-connector"
    BOLDSIGN = "test-boldsign-connector"
    KEAP = "test-keap-connector"
    AMAZON = "test-amazon-connector"
    SALESFORCE = "test-salesforce-connector"
    ZOHO_BOOKS = "test-zoho_books-connector"
    GORGIAS = "test-gorgias-connector"
    HACKERRANK_WORK = "test-hackerrank-work-connector"
    REDDIT = "test-reddit-connector"
    SERVICEM8 = "test-servicem8-connector"
    SHORTCUT = "test-shortcut-connector"
    FRONT = "test-front-connector"
    SURVEY_MONKEY = "test-survey-monkey-connector"
    WAKATIME = "test-wakatime-connector"
    ZOHO_INVENTORY = "test-zoho_inventory-connector"
    DISCORD = "test-discord-connector"
    TWITCH = "test-twitch-connector"
    ATLASSIAN = "test-atlassian-connector"
    HARVEST = "test-harvest-connector"
    CALENDLY = "test-calendly-connector"
    GOOGLE_CALENDAR = "test-google_calendar-connector"
    BAMBOOHR = "test-bamboohr-connector"
    GITHUB = "test-github-connector"
    DEEL = "test-deel-connector"
    GITLAB = "test-gitlab-connector"
    HUBSPOT = "test-hubspot-connector"
    SLACKBOT = "test-slackbot-connector"
    YANDEX = "test-yandex-connector"
    BRAINTREE = "test-braintree-connector"
    ZOHO_INVOICE = "test-zoho_invoice-connector"
    FRESHBOOKS = "test-freshbooks-connector"
    AUTH0 = "test-auth0-connector"
    ONE_DRIVE = "test-one-drive-connector"
    OKTA = "test-okta-connector"
    ZOHO_DESK = "test-zoho_desk-connector"
    SMARTRECRUITERS = "test-smartrecruiters-connector"
    FACEBOOK = "test-facebook-connector"
    MURAL = "test-mural-connector"
    WORKABLE = "test-workable-connector"
    YOUTUBE = "test-youtube-connector"
    ADOBE = "test-adobe-connector"
    SQUARE = "test-square-connector"
    ASHBY = "test-ashby-connector"
    HIGHLEVEL = "test-highlevel-connector"
    GOOGLE_DRIVE = "test-google-drive-connector"
    EPIC_GAMES = "test-epic-games-connector"
    TODOIST = "test-todoist-connector"
    ZOHO_BIGIN = "test-zoho_bigin-connector"
    AMPLITUDE = "test-amplitude-connector"
    HEROKU = "test-heroku-connector"
    SAGE = "test-sage-connector"
    WAVE_ACCOUNTING = "test-wave-accounting-connector"
    CLOSE = "test-close-connector"
    PANDADOC = "test-pandadoc-connector"
    BLACKBAUD = "test-blackbaud-connector"
    GURU = "test-guru-connector"
    SERPAPI = "test-serpapi-connector"
    SMUGMUG = "test-smugmug-connector"
    BATTLENET = "test-battlenet-connector"
    LINKHUT = "test-linkhut-connector"
    XERO = "test-xero-connector"
    APIFY = "test-apify-connector"
    LINEARSANDBOX = "test-linearsandbox-connector"
    ZENDESK = "test-zendesk-connector"
    ZOHO_MAIL = "test-zoho_mail-connector"
    RING_CENTRAL = "test-ring-central-connector"
    CODEINTERPRETER = "test-CodeInterpreter-connector"
    GOOGLECALENDAR = "test-googlecalendar-connector"
    ACCELO = "test-accelo-connector"

class Action(Enum):
    def __init__(self, service, action):
        self.service = service
        self.action = action

    ASANA_CREATE_SUBTASK = ("asana", "asana_create_subtask")
    ASANA_GET_SUBTASKS = ("asana", "asana_get_subtasks")
    TRELLO_CREATE_TRELLO_LIST = ("trello", "trello_create_trello_list")
    TRELLO_CREATE_TRELLO_CARD = ("trello", "trello_create_trello_card")
    TRELLO_GET_TRELLO_BOARD_CARDS = ("trello", "trello_get_trello_board_cards")
    TRELLO_DELETE_TRELLO_CARD = ("trello", "trello_delete_trello_card")
    TRELLO_ADD_TRELLO_CARD_COMMENT = ("trello", "trello_add_trello_card_comment")
    TRELLO_CREATE_TRELLO_LABEL = ("trello", "trello_create_trello_label")
    TRELLO_UPDATE_TRELLO_BOARD = ("trello", "trello_update_trello_board")
    TRELLO_GET_ABOUT_ME = ("trello", "trello_get_about_me")
    TRELLO_SEARCH_TRELLO = ("trello", "trello_search_trello")
    TRELLO_SEARCH_TRELLO_MEMBER = ("trello", "trello_search_trello_member")
    TRELLO_UPDATE_TRELLO_CARD = ("trello", "trello_update_trello_card")
    TRELLO_GET_TRELLO_MEMBER_BOARD = ("trello", "trello_get_trello_member_board")
    LINEAR_CREATE_LINEAR_ISSUE = ("linear", "linear_create_linear_issue")
    LINEAR_LIST_LINEAR_PROJECTS = ("linear", "linear_list_linear_projects")
    LINEAR_LIST_LINEAR_TEAMS = ("linear", "linear_list_linear_teams")
    GMAIL_SEND_EMAIL = ("gmail", "gmail_send_email")
    GMAIL_CREATE_EMAIL_DRAFT = ("gmail", "gmail_create_email_draft")
    GMAIL_FIND_EMAIL_ID = ("gmail", "gmail_find_email_id")
    GMAIL_FETCH_LAST_THREE_MESSAGES = ("gmail", "gmail_fetch_last_three_messages")
    GMAIL_ADD_LABEL_TO_EMAIL = ("gmail", "gmail_add_label_to_email")
    GMAIL_LIST_LABELS = ("gmail", "gmail_list_labels")
    GMAIL_FETCH_MESSAGE_BY_THREAD_ID = ("gmail", "gmail_fetch_message_by_thread_id")
    GMAIL_REPLY_TO_THREAD = ("gmail", "gmail_reply_to_thread")
    GMAIL_FETCH_EMAILS_WITH_LABEL = ("gmail", "gmail_fetch_emails_with_label")
    SLACK_SEND_SLACK_MESSAGE = ("slack", "slack_send_slack_message")
    SLACK_LIST_SLACK_CHANNELS = ("slack", "slack_list_slack_channels")
    SLACK_LIST_SLACK_MEMBERS = ("slack", "slack_list_slack_members")
    SLACK_LIST_SLACK_MESSAGES = ("slack", "slack_list_slack_messages")
    DROPBOX_GET_ABOUT_ME = ("dropbox", "dropbox_get_about_me")
    CLICKUP_CREATE_TASK = ("clickup", "clickup_create_task")
    CLICKUP_GET_TASKS = ("clickup", "clickup_get_tasks")
    CLICKUP_GET_TASK = ("clickup", "clickup_get_task")
    CLICKUP_CREATE_LIST = ("clickup", "clickup_create_list")
    CLICKUP_GET_LISTS = ("clickup", "clickup_get_lists")
    CLICKUP_GET_SPACES = ("clickup", "clickup_get_spaces")
    CLICKUP_CREATE_SPACE = ("clickup", "clickup_create_space")
    CLICKUP_CREATE_FOLDER = ("clickup", "clickup_create_folder")
    CLICKUP_GET_FOLDERS = ("clickup", "clickup_get_folders")
    NOTION_GET_ABOUT_ME = ("notion", "notion_get_about_me")
    NOTION_ADD_NOTION_PAGE_CHILDREN = ("notion", "notion_add_notion_page_children")
    NOTION_ARCHIVE_NOTION_PAGE = ("notion", "notion_archive_notion_page")
    NOTION_CREATE_NOTION_DATABASE = ("notion", "notion_create_notion_database")
    NOTION_CREATE_PAGE_COMMENT = ("notion", "notion_create_page_comment")
    NOTION_CREATE_NOTION_PAGE = ("notion", "notion_create_notion_page")
    NOTION_DELETE_NOTION_PAGE_CHILDREN = ("notion", "notion_delete_notion_page_children")
    NOTION_FETCH_NOTION_COMMENT = ("notion", "notion_fetch_notion_comment")
    NOTION_FETCH_NOTION_DATABASE = ("notion", "notion_fetch_notion_database")
    NOTION_FETCH_NOTION_PAGE = ("notion", "notion_fetch_notion_page")
    NOTION_SEARCH_NOTION_PAGE = ("notion", "notion_search_notion_page")
    NOTION_UPDATE_NOTION_DATABASE = ("notion", "notion_update_notion_database")
    NOTION_FETCH_NOTION_BLOCK = ("notion", "notion_fetch_notion_block")
    NOTION_FETCH_NOTION_CHILD_BLOCK = ("notion", "notion_fetch_notion_child_block")
    TYPEFORM_GET_ABOUT_ME = ("typeform", "typeform_get_about_me")
    GITHUB_CREATE_ISSUE = ("github", "github_create_issue")
    GITHUB_LIST_GITHUB_REPOS = ("github", "github_list_github_repos")
    GITHUB_STAR_REPO = ("github", "github_star_repo")
    GITHUB_GET_ABOUT_ME = ("github", "github_get_about_me")
    GITHUB_FETCH_README = ("github", "github_fetch_readme")
    GITHUB_GET_COMMITS = ("github", "github_get_commits")
    GITHUB_GET_COMMITS_WITH_CODE = ("github", "github_get_commits_with_code")
    GITHUB_GET_PATCH_FOR_COMMIT = ("github", "github_get_patch_for_commit")
    SLACKBOT_SEND_SLACK_MESSAGE = ("slackbot", "slackbot_send_slack_message")
    SLACKBOT_LIST_SLACK_CHANNELS = ("slackbot", "slackbot_list_slack_channels")
    SLACKBOT_LIST_SLACK_MEMBERS = ("slackbot", "slackbot_list_slack_members")
    SLACKBOT_LIST_SLACK_MESSAGES = ("slackbot", "slackbot_list_slack_messages")
    SERPAPI_SEARCH = ("serpapi", "serpapi_search")
    APIFY_LIST_APIFY_ACTORS = ("apify", "apify_list_apify_actors")
    APIFY_CREATE_APIFY_ACTOR = ("apify", "apify_create_apify_actor")
    APIFY_GET_ACTOR_ID = ("apify", "apify_get_actor_id")
    APIFY_SEARCH_STORE = ("apify", "apify_search_store")
    APIFY_GET_LAST_RUN_DATA = ("apify", "apify_get_last_run_data")
    APIFY_LIST_APIFY_TASKS = ("apify", "apify_list_apify_tasks")
    ZENDESK_CREATE_ZENDESK_ORGANIZATION = ("zendesk", "zendesk_create_zendesk_organization")
    ZENDESK_DELETE_ZENDESK_ORGANIZATION = ("zendesk", "zendesk_delete_zendesk_organization")
    ZENDESK_COUNT_ZENDESK_ORGANIZATIONS = ("zendesk", "zendesk_count_zendesk_organizations")
    ZENDESK_GET_ZENDESK_ORGANIZATION = ("zendesk", "zendesk_get_zendesk_organization")
    ZENDESK_GET_ALL_ZENDESK_ORGANIZATIONS = ("zendesk", "zendesk_get_all_zendesk_organizations")
    ZENDESK_UPDATE_ZENDESK_ORGANIZATION = ("zendesk", "zendesk_update_zendesk_organization")
    ZENDESK_CREATE_ZENDESK_TICKET = ("zendesk", "zendesk_create_zendesk_ticket")
    ZENDESK_DELETE_ZENDESK_TICKET = ("zendesk", "zendesk_delete_zendesk_ticket")
    ZENDESK_GET_ABOUT_ME = ("zendesk", "zendesk_get_about_me")
    GOOGLECALENDAR_CREATE_GOOGLE_EVENT = ("googlecalendar", "googlecalendar_create_google_event")
    GOOGLECALENDAR_REMOVE_ATTENDEE = ("googlecalendar", "googlecalendar_remove_attendee")
    GOOGLECALENDAR_FIND_EVENT = ("googlecalendar", "googlecalendar_find_event")
    GOOGLECALENDAR_CHECK_ATTENDEES = ("googlecalendar", "googlecalendar_check_attendees")
    GOOGLECALENDAR_DELETE_GOOGLE_EVENT = ("googlecalendar", "googlecalendar_delete_google_event")
    GOOGLECALENDAR_UPDATE_GOOGLE_EVENT = ("googlecalendar", "googlecalendar_update_google_event")

class Trigger(Enum):
    def __init__(self, service, trigger):
        self.service = service
        self.trigger = trigger

    SLACK_NEW_MESSAGE = ("slack", "slack_receive_message")
    GITHUB_PULL_REQUEST_EVENT = ("github", "github_pull_request_event")
    GITHUB_COMMIT_EVENT = ("github", "github_commit_event")
    SLACKBOT_NEW_MESSAGE = ("slackbot", "slackbot_receive_message")
