
# This file was generated by 'versioneer.py' (0.23) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-04-15T12:05:52+0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "34c2d31484143b7b5c6130927ed4efde93a27a0f",
 "version": "5.13.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
